[[constraint]]
  name = "github.com/Juniper/go-netconf"
  version = "0.1.1"

[[constraint]]
  name = "github.com/braintree/manners"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/cdevr/WapSNMP"

[[constraint]]
  branch = "master"
  name = "github.com/cloudwan/goose"

[[constraint]]
  name = "github.com/codegangsta/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.8"

[[constraint]]
  name = "github.com/coreos/go-etcd"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/cyberdelia/go-metrics-graphite"

[[constraint]]
  name = "github.com/ddliu/motto"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/drone/routes"

[[constraint]]
  name = "github.com/flosch/pongo2"
  version = "3.0.0"

[[constraint]]
  name = "github.com/go-martini/martini"
  revision = "b174c4f35f9f3805e960be6286d888bc79534755"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/gophercloud/gophercloud"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  name = "github.com/k0kubun/pp"
  version = "2.3.0"

[[constraint]]
  name = "github.com/kr/pretty"
  version = "0.1.0"

[[constraint]]
  name = "github.com/lann/squirrel"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/lestrrat/go-server-starter"

[[constraint]]
  branch = "master"
  name = "github.com/martini-contrib/staticbin"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.9.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/hashstructure"

[[constraint]]
  branch = "master"
  name = "github.com/mohae/deepcopy"

[[constraint]]
  branch = "master"
  name = "github.com/nati/go-fakedb"

[[constraint]]
  branch = "master"
  name = "github.com/nati/yaml"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.3.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.0"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/rcrowley/go-metrics"

[[constraint]]
  branch = "master"
  name = "github.com/robertkrimen/otto"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/serenize/snaker"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  branch = "master"
  name = "github.com/streamrail/concurrent-map"

[[constraint]]
  name = "github.com/twinj/uuid"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/tylerb/gls"

[[constraint]]
  name = "github.com/vattle/sqlboiler"
  version = "2.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/xeipuuv/gojsonpointer"

[[constraint]]
  name = "github.com/xeipuuv/gojsonschema"
  revision = "93e72a773fade158921402d6a24c819b48aba29d"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"
