database:
    type: "mysql"
    connection: "root@/gohan_test"
    drop_on_create: true
schemas:
    - "../etc/schema/gohan.json"
    - "../tests/test_abstract_schema.yaml"
    - "../tests/test_schema.yaml"
    - "../tests/test_two_same_relations_schema.yaml"
address: ":19090"
document_root: "embed"
etcd:
    - "http://127.0.0.1:4001"
keystone:
    use_keystone: true
    fake: true
    auth_url: "http://localhost:19090/v2.0"
    user_name: "admin"
    tenant_name: "admin"
    password: "gohan"
cors: "*"
# allowed levels  "CRITICAL", "ERROR", "WARNING", "NOTICE", "INFO", "DEBUG",
logging:
    stderr:
        enabled: true
        level: CRITICAL
    file:
        enabled: true
        level: CRITICAL
        filename: ./gohan.log
